-- PRD-01/02/03/04：商品平台真值、同步来源、事件、指标和可恢复批量任务。

ALTER TABLE xianyu_goods
    ADD COLUMN outer_id VARCHAR(128) NULL AFTER xy_good_id,
    ADD COLUMN product_source VARCHAR(32) NOT NULL DEFAULT 'PLATFORM_LIST_SYNC' AFTER xianyu_account_id,
    ADD COLUMN publish_channel VARCHAR(40) NULL AFTER product_source,
    ADD COLUMN item_type VARCHAR(24) NULL AFTER publish_channel,
    ADD COLUMN category_id VARCHAR(100) NULL AFTER item_type,
    ADD COLUMN category_name VARCHAR(255) NULL AFTER category_id,
    ADD COLUMN business_mode VARCHAR(64) NULL AFTER category_name,
    ADD COLUMN condition_code VARCHAR(64) NULL AFTER business_mode,
    ADD COLUMN original_price DECIMAL(12,2) NULL AFTER sold_price,
    ADD COLUMN shipping_fee DECIMAL(12,2) NULL AFTER original_price,
    ADD COLUMN shipping_type VARCHAR(32) NULL AFTER shipping_fee,
    ADD COLUMN stock INT NULL AFTER sku_count,
    ADD COLUMN sync_status VARCHAR(24) NOT NULL DEFAULT 'PARTIAL' AFTER status,
    ADD COLUMN coverage_status VARCHAR(24) NOT NULL DEFAULT 'PARTIAL' AFTER sync_status,
    ADD COLUMN platform_updated_time DATETIME(3) NULL AFTER coverage_status,
    ADD COLUMN last_synced_time DATETIME(3) NULL AFTER platform_updated_time,
    ADD COLUMN last_sync_request_id VARCHAR(80) NULL AFTER last_synced_time,
    ADD COLUMN platform_snapshot_hash CHAR(64) NULL AFTER last_sync_request_id,
    ADD COLUMN last_sync_error_code VARCHAR(80) NULL AFTER platform_snapshot_hash,
    ADD COLUMN last_sync_error_message VARCHAR(1000) NULL AFTER last_sync_error_code,
    ADD KEY idx_goods_source_channel (tenant_id, product_source, publish_channel),
    ADD KEY idx_goods_outer_id (tenant_id, outer_id),
    ADD KEY idx_goods_sync_state (tenant_id, sync_status, coverage_status, last_synced_time);

UPDATE xianyu_goods
   SET last_synced_time = updated_time,
       platform_updated_time = updated_time
 WHERE last_synced_time IS NULL;

CREATE TABLE xianyu_goods_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    xianyu_account_id BIGINT NOT NULL,
    xy_goods_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(48) NOT NULL,
    event_origin VARCHAR(32) NOT NULL,
    outcome_state VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    data_source VARCHAR(32) NOT NULL,
    operator_user_id BIGINT NULL,
    operator_username VARCHAR(50) NULL,
    request_id VARCHAR(80) NULL,
    idempotency_key VARCHAR(100) NULL,
    before_json LONGTEXT NULL,
    after_json LONGTEXT NULL,
    field_diff_json LONGTEXT NULL,
    raw_snapshot_hash CHAR(64) NULL,
    platform_response_code VARCHAR(100) NULL,
    error_message VARCHAR(1000) NULL,
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_goods_event_request (tenant_id, xianyu_account_id, xy_goods_id, event_type, request_id),
    KEY idx_goods_event_timeline (tenant_id, xianyu_account_id, xy_goods_id, created_time),
    KEY idx_goods_event_outcome (tenant_id, outcome_state, created_time),
    CONSTRAINT fk_goods_event_account FOREIGN KEY (xianyu_account_id) REFERENCES xianyu_account (id) ON DELETE CASCADE,
    CONSTRAINT fk_goods_event_operator FOREIGN KEY (operator_user_id) REFERENCES sys_user (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE xianyu_goods_metric_daily (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    xianyu_account_id BIGINT NOT NULL,
    xy_goods_id VARCHAR(100) NOT NULL,
    metric_date DATE NOT NULL,
    exposure_count BIGINT NULL,
    visitor_count BIGINT NULL,
    click_count BIGINT NULL,
    favorite_count BIGINT NULL,
    inquiry_count BIGINT NULL,
    paid_order_count BIGINT NULL,
    paid_amount DECIMAL(14,2) NULL,
    conversion_rate DECIMAL(9,6) NULL,
    source VARCHAR(32) NOT NULL,
    coverage_status VARCHAR(24) NOT NULL DEFAULT 'PARTIAL',
    synced_at DATETIME(3) NULL,
    request_id VARCHAR(80) NULL,
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_goods_metric_daily (tenant_id, xianyu_account_id, xy_goods_id, metric_date, source),
    KEY idx_goods_metric_window (tenant_id, xianyu_account_id, metric_date, xy_goods_id),
    CONSTRAINT fk_goods_metric_account FOREIGN KEY (xianyu_account_id) REFERENCES xianyu_account (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE xianyu_goods_batch_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    batch_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(80) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    selection_mode VARCHAR(24) NOT NULL,
    selection_query_json LONGTEXT NULL,
    operation_params_json LONGTEXT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
    selected_count INT NOT NULL,
    conflict_count INT NOT NULL DEFAULT 0,
    executable_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    unknown_count INT NOT NULL DEFAULT 0,
    max_operations_per_minute INT NOT NULL DEFAULT 10,
    confirmation_summary VARCHAR(1000) NOT NULL,
    operator_user_id BIGINT NULL,
    operator_username VARCHAR(50) NULL,
    started_time DATETIME(3) NULL,
    completed_time DATETIME(3) NULL,
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_goods_batch_id (tenant_id, batch_id),
    UNIQUE KEY uk_goods_batch_request (tenant_id, request_id),
    KEY idx_goods_batch_queue (tenant_id, status, created_time),
    CONSTRAINT fk_goods_batch_operator FOREIGN KEY (operator_user_id) REFERENCES sys_user (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE xianyu_goods_batch_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    batch_job_id BIGINT NOT NULL,
    batch_id VARCHAR(64) NOT NULL,
    xianyu_account_id BIGINT NOT NULL,
    xy_goods_id VARCHAR(100) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
    conflict_code VARCHAR(64) NULL,
    conflict_message VARCHAR(1000) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    next_retry_time DATETIME(3) NULL,
    outcome_state VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    platform_response_code VARCHAR(100) NULL,
    result_json LONGTEXT NULL,
    error_message VARCHAR(1000) NULL,
    started_time DATETIME(3) NULL,
    completed_time DATETIME(3) NULL,
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_goods_batch_item (tenant_id, batch_job_id, xianyu_account_id, xy_goods_id),
    KEY idx_goods_batch_item_queue (tenant_id, status, next_retry_time, xianyu_account_id),
    KEY idx_goods_batch_item_goods (tenant_id, xianyu_account_id, xy_goods_id, created_time),
    CONSTRAINT fk_goods_batch_item_job FOREIGN KEY (batch_job_id) REFERENCES xianyu_goods_batch_job (id) ON DELETE CASCADE,
    CONSTRAINT fk_goods_batch_item_account FOREIGN KEY (xianyu_account_id) REFERENCES xianyu_account (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
