-- IM-01/02 + NTF-01：服务端未读、人工接管、发送结果与站内通知事件。

ALTER TABLE conversation_assignment
    ADD COLUMN unread_count INT NOT NULL DEFAULT 0 AFTER buyer_user_id,
    ADD COLUMN last_read_message_time BIGINT NULL AFTER unread_count,
    ADD COLUMN last_read_at DATETIME(3) NULL AFTER last_read_message_time,
    ADD COLUMN last_read_by BIGINT NULL AFTER last_read_at,
    ADD COLUMN manual_takeover_state VARCHAR(24) NOT NULL DEFAULT 'AUTO' AFTER last_read_by,
    ADD COLUMN manual_takeover_until DATETIME(3) NULL AFTER manual_takeover_state,
    ADD COLUMN auto_reply_state VARCHAR(24) NOT NULL DEFAULT 'UNKNOWN' AFTER manual_takeover_until,
    ADD COLUMN history_sync_status VARCHAR(24) NOT NULL DEFAULT 'PARTIAL' AFTER auto_reply_state,
    ADD COLUMN history_coverage_status VARCHAR(24) NOT NULL DEFAULT 'PARTIAL' AFTER history_sync_status,
    ADD COLUMN history_last_synced_time DATETIME(3) NULL AFTER history_coverage_status,
    ADD COLUMN history_last_error VARCHAR(500) NULL AFTER history_last_synced_time,
    ADD KEY idx_conversation_unread (tenant_id, unread_count, last_message_time),
    ADD KEY idx_conversation_takeover (tenant_id, manual_takeover_state, manual_takeover_until),
    ADD CONSTRAINT fk_conversation_last_reader FOREIGN KEY (last_read_by) REFERENCES sys_user (id) ON DELETE SET NULL;

CREATE TABLE xianyu_message_send_attempt (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    xianyu_account_id BIGINT NOT NULL,
    session_id VARCHAR(100) NOT NULL,
    recipient_user_id VARCHAR(100) NOT NULL,
    xy_goods_id VARCHAR(100) NULL,
    content_type VARCHAR(16) NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    content_excerpt VARCHAR(200) NULL,
    request_id VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    outcome_state VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    platform_ack_code VARCHAR(100) NULL,
    error_message VARCHAR(500) NULL,
    operator_user_id BIGINT NULL,
    operator_username VARCHAR(50) NULL,
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_message_attempt_request (tenant_id, request_id),
    KEY idx_message_attempt_session (tenant_id, xianyu_account_id, session_id, created_time),
    KEY idx_message_attempt_outcome (tenant_id, outcome_state, updated_time),
    CONSTRAINT fk_message_attempt_account FOREIGN KEY (xianyu_account_id) REFERENCES xianyu_account (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_attempt_user FOREIGN KEY (operator_user_id) REFERENCES sys_user (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE xianyu_notification_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    event_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    xianyu_account_id BIGINT NULL,
    business_object_type VARCHAR(40) NULL,
    business_object_id VARCHAR(128) NULL,
    severity VARCHAR(16) NOT NULL DEFAULT 'INFO',
    title VARCHAR(200) NOT NULL,
    content_summary VARCHAR(1000) NULL,
    source VARCHAR(32) NOT NULL,
    dedupe_key VARCHAR(191) NOT NULL,
    target_route VARCHAR(500) NULL,
    data_json TEXT NULL,
    read_time DATETIME(3) NULL,
    read_by BIGINT NULL,
    handling_status VARCHAR(24) NOT NULL DEFAULT 'UNHANDLED',
    handled_time DATETIME(3) NULL,
    handled_by BIGINT NULL,
    handling_note VARCHAR(1000) NULL,
    occurred_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_notification_event_id (tenant_id, event_id),
    UNIQUE KEY uk_notification_event_dedupe (tenant_id, event_type, dedupe_key),
    KEY idx_notification_inbox (tenant_id, read_time, handling_status, occurred_time),
    KEY idx_notification_account (tenant_id, xianyu_account_id, occurred_time),
    CONSTRAINT fk_notification_event_account FOREIGN KEY (xianyu_account_id) REFERENCES xianyu_account (id) ON DELETE SET NULL,
    CONSTRAINT fk_notification_event_reader FOREIGN KEY (read_by) REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_notification_event_handler FOREIGN KEY (handled_by) REFERENCES sys_user (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
